# Generated by Django 5.2.3 on 2025-07-05 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyoffer',
            name='license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='licenses.license'),
        ),
        migrations.AddField(
            model_name='selloffer',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
