# Generated by Django 5.2.3 on 2025-07-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_buyoffer_license_selloffer_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('zip_file', models.FileField(upload_to='robots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
