# Generated by Django 5.2.3 on 2025-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0003_robot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
